# Generated by Django 2.2.6 on 2019-10-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listo', '0004_auto_20191022_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
